require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../mobile_sdk/SalesforceMobileSDK-iOS/mobilesdk_pods'

platform :ios, '14.0'
use_modular_headers!

project 'SalesforceMobileSDKMapsted.xcodeproj'

plugin 'cocoapods-user-defined-build-types'
enable_user_defined_build_types!

target 'SalesforceMobileSDKMapsted' do
  source 'https://cdn.cocoapods.org/'
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.disabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  use_mobile_sdk!(:path => '../mobile_sdk/SalesforceMobileSDK-iOS')

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"

  pod 'SalesforceReact', :path => '../node_modules/react-native-force'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  
  # Mapsted map start
  source 'https://cdn.cocoapods.org/'
  #source 'https://github.com/Mapsted/podspec.git'
  source 'https://github.com/Mapsted/podspec-simulator.git'
  #use_frameworks!
  pod 'mapsted-sdk-map-ui', '~> 5.0', :build_type => :dynamic_framework
  # Mapsted map end


  target 'SalesforceMobileSDKMapstedTests' do
    inherit! :complete
    # Pods for testing
  end

  pre_install do |installer|
    # Mobile SDK pre install
    mobile_sdk_pre_install(installer)
  end

  post_install do |installer|
    PLIST_BUDDY_PATH = '/usr/libexec/PlistBuddy'

  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = ''
        config.build_settings['ARCHS'] = '${ARCHS_STANDARD_64_BIT}'
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        # Workaround for RN 0.72 and Reanimated 2.10.0
        if target.name == "hermes-engine"
                installer.pods_project.files.each do |fileref|
                  if fileref.path.end_with? "hermes.xcframework"
                    hermes_plist_file = "#{fileref.real_path}/Info.plist"
                    # Patch Hermes to remove the debug symbols entry from the Info.plist (as it's not shipped with it)
                    # This might be removed once Hermes starts to ship with Debug symbols or we remove our
                    # direct dependency from the Main iOS target on "hermes.xcframework"
                    Open3.capture3(PLIST_BUDDY_PATH, '-c', 'Delete :AvailableLibraries:0:DebugSymbolsPath', hermes_plist_file)
                    Open3.capture3(PLIST_BUDDY_PATH, '-c', 'Delete :AvailableLibraries:1:DebugSymbolsPath', hermes_plist_file)
                    Open3.capture3(PLIST_BUDDY_PATH, '-c', 'Delete :AvailableLibraries:2:DebugSymbolsPath', hermes_plist_file)
                  end
                end
              end
        if target.name === "RNReanimated" or target.name === "RCT-Folly"
                config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
              end
      end
    end
  # Comment the following if you do not want the SDK to emit signpost events for instrumentation. Signposts are  enabled for non release version of the app.
  signposts_post_install(installer)

  # React native post install
  react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
  )

  # Cocoapods workaround for M1 machines
  __apply_Xcode_12_5_M1_post_install_workaround(installer)

  # Mobile SDK post install
  mobile_sdk_post_install(installer)
  end
end
